language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - libfuse2
install:
  - pip install .
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=splitviewfuse
after_success:
  - coveralls
before_deploy:
- git clone https://github.com/seiferma/travis-utils.git
deploy:
  provider: script
  script: travis-utils/python_deploy.sh
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = '2.7'"
env:
  global:
  - DEPLOY_URL=https://pypi.python.org/pypi
  - DEPLOY_USER=seiferma
  - secure: "ODXRflklJo0Lx2gMil+w9UNOWTkZx7V+pxjOV9TLFTZq/ZJNjnCzkKWLYzYKzqdldge/UpyfbltOXYuRnLdVFtRZ0wHDkdxhXayOAAuedS05qWaTSt+S/y8H20z3o3+35uuxpJp2h/7W8QNSJg6BFoNrJrV3XmlX3c1xLKaR0os="