language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - libfuse2
install:
- pip install .
script: nosetests
deploy:
  provider: pypi
  server: https://pypi.python.org/pypi
  user: seiferma
  password:
    secure: Ok03/5xX2YYIob5s3NaW2sxLdRvhL96auL33rgIVXln1WdIakgP991yXrEC3b6fxiQdIWoVaPXZrfc3Ttq8InfcVylGKntTk3qluG8yjgFXonGmymEpWzJ/BufLergN0zjMs6n0MasX6JMM7vJ2rRGL8maqLJTx/Jf8e4qCDNqA=
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = '2.7'
after_deploy:
  - git clone https://github.com/seiferma/travis-utils.git
  - python travis-utils/validate_pypi_2x.py -v || exit 1

