language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - libfuse2
install:
  - pip install .
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=splitviewfuse
after_success:
  - coveralls
deploy:
  provider: pypi
  server: https://pypi.python.org/pypi
  user: seiferma
  password:
    secure: C62GZK1Kc8CwMTPu1Snoswkfpa6wE/N7H/kDvKlG1QOerzPOhUxK2KrJzgB6kCXxw9OyFPrgC8T5aDufqMEoSuDZYlni9OI/Yhvg9Mzx/N67oxcMMtiHgbzK2s9KQujf9V23GOmlrGkVk/c2/14AJQpu3jhgCrDUM5bp68Pyi8k=
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = '2.7'
after_deploy:
  - git clone https://github.com/seiferma/travis-utils.git
  - python travis-utils/validate_pypi_2x.py -v || exit 1
